apiVersion: v1
kind: Namespace
metadata:
  name: alpha
  labels:
    team: alpha
    managed-by: platform-team
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: alpha-quota
  namespace: alpha
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "50"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: alpha-limits
  namespace: alpha
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
